- src/App.less
- src/components/club/ClubList.js
> fixed aligns

- .gitignore
- src/components/header/AuthMenu.js
- src/components/profile/Login.js
- src/components/profile/LoginTitle.js
- src/components/profile/Profile.js
- src/components/profile/Registration.js
- src/components/profile/сss/Profile.less
- src/service/UserService.js
> added form to login for user and for clubowners (only ui)

- src/App.less
- src/components/Loader.js
- src/components/clubs/ClubCardItem.js
- src/components/clubs/Search.js
- src/components/map/ClubItem.js
- src/components/map/MapClubList.js
- src/components/map/MapComponent.js
- src/components/map/MapContainer.js
- src/components/map/css/MapClubList.css
- src/context/SearchContext.js
> Map change

- src/components/map/Cities.js
- src/components/map/ClubItem.js
- src/components/map/MapClubList.js
- src/components/map/MapComponent.js
- src/components/map/MapContainer.js
> add centering of the map after clicking on the marker or club list item

- src/components/clubPage/sider/SimilarClubs.js
- src/components/registration/Registration.js
- src/components/registration/RegistrationInput.js
- src/components/registration/RegistrationRoles.js
- src/components/registration/сss/Registration.less
- src/service/UserService.js
> fixed reg page

- src/components/clubPage/comments/CommentEditComponent.js
- src/service/ComplaintService.js
- src/service/FeedbackService.js
> Added complaint processing

- src/components/admin/city/CityTable.js
- src/service/CategoryService.js
> some fixes

- src/App.js
- src/components/admin/question/AddQuestion.js
- src/components/admin/question/QuestionTable.js
- src/components/admin/question/css/AddQuestion.css
- src/components/serviceInUkr/ServiceInUkr.js
- src/service/QuestionService.js
> added question table and updated ServiceInUkr.js

- src/App.js
- src/components/admin/users/UsersTable.js
- src/components/registration/Registration.js
> some fixes for preparing war

- src/components/EditableColumn.js
- src/components/admin/question/AddQuestion.js
- src/components/admin/question/QuestionTable.js
- src/components/header/AuthMenu.js
> added textarea to editable table

- src/App.js
- src/components/admin/station/AddStation.js
- src/components/admin/station/StationTable.js
- src/components/admin/station/css/AddStation.css
- src/components/header/AuthMenu.js
- src/service/StationService.js
> Added admin page for editing stations

- package.json
- src/App.js
- src/components/admin/club/approveClub/ApproveClubTable.js
- src/components/admin/club/changeOwner/ChangeOwnerFooter.js
- src/components/admin/club/changeOwner/ChangeOwnerTable.js
- src/components/header/AuthMenu.js
- src/service/ClubService.js
- src/service/UserService.js
> added approve-club page and change-owner page for admins

- src/components/footer/FooterDonate.js
> Bug fix spelling mistake in donateFooter

- .env.development
- src/components/header/AuthMenu.js
- src/components/header/css/authMenu.css
- src/components/login/Login.js
> Fix the login buttom background

- src/App.less
- src/components/footer/FooterSocials.js
- src/components/footer/css/Footer.less
- src/components/header/NavMenu.js
> Fixed logo margin, facebook logo and nav-menu underlined item

- src/App.less
- src/components/footer/FooterSocials.js
- src/components/footer/css/Footer.less
- src/components/header/AuthMenu.js
- src/components/mainPage/css/AboutChallenge.css
- src/components/mainPage/css/CarouselItems.css
> Fixed buttons font size, copyright section

- src/components/clubList/ClubList.js
- src/components/clubList/ClubListItemInfo.js
- src/components/clubPage/sider/SocialMedia.js
> fix bug on click on the club item

- src/App.less
> Changed font size of city name in header

- src/components/Search.js
- src/components/clubList/ClubList.js
- src/service/ClubService.js
> Bug fix/search field

- package.json
- src/App.js
- src/components/EditableColumn.js
- src/components/admin/category/AddCategory.js
- src/components/admin/category/CategoryTable.js
- src/components/admin/category/css/AddCategory.css
- src/components/admin/station/StationTable.js
- src/components/header/AuthMenu.js
- src/service/CategoryService.js
> Develop UI and back form for add/edit categories

- src/components/Search.js
> club items change each time when user change input line

- package.json
- src/components/admin/category/CategoryTable.js
> Remove react-color dependency

- src/components/AboutProject/AboutProject.js
- src/components/serviceInUkr/ServiceInUkr.js
> fix spelling mistake on button label

- src/components/admin/category/CategoryTable.js
- src/service/CategoryService.js
> fix UI form for edit category

- src/components/admin/category/AddCategory.js
- src/components/admin/category/CategoryTable.js
- src/service/CategoryService.js
> fix bugs add and edit category, upload icon in category

- src/components/admin/category/AddCategory.js
> add_color_menu_for_addCategory_form

- src/App.less
> Changed font size of input text

- src/components/admin/category/CategoryTable.js
- src/components/map/Categories.js
> fix bug ui table category

- src/components/admin/category/CategoryTable.js
- src/components/header/AuthMenu.js
- src/components/map/Categories.js
> Add sort categories on backend

- src/components/clubList/ClubListControl.js
> fix bug 408 in ClubListControl

- src/components/verifyPage/VerifyPage.js
- src/service/VerifyService.js
> fix verify user by email

- src/components/clubPage/content/PageRating.js
> fixed label, that shows incorrect feedback

- src/components/addClub/location/AddLocationModal.js
> Add regex on phone number field

- src/components/map/css/ClubItem.css
> fixed clubs title

- src/components/userPage/content/css/UserContent.less
> fixed the wrong button color

- src/App.less
> fixButtonPosition (№364)

- src/components/addClub/location/AddLocationModal.js
> Add regex on location name field

- src/components/addClub/location/AddLocationModal.js
> fixed incorrectly named textbox

- src/components/userPage/sider/css/Sider.less
> fix alignment and font button

- src/components/header/AuthMenu.js
> Fix spelling mistake

- src/App.less
> fixed header screen resolution

- src/App.js
- src/components/log/LogByNameComponent.js
- src/components/log/LogComponent.js
- src/components/log/css/LogComponent.css
- src/service/LogService.js
> add read logs

- src/components/mainPage/MainCategories.js
> fixed redirect on footer on the page of the clubs

- src/components/footer/FooterSocials.js
- src/components/log/LogByNameComponent.js
- src/components/log/LogComponent.js
- src/components/log/css/LogComponent.css
- src/service/LogService.js
> add read logs style and fix request. Fix FooterSocials.js logo

- src/components/clubList/ClubListComponent.js
> Fix advanced search slider pop-up

- src/components/clubList/ClubListSider.js
> fixed bug 404

- src/components/editClub/tabs/DescriptionTab.js
> Added restriction on description field

- src/App.less
> fix burger menu

- src/components/Search.js
- src/components/clubList/ClubListComponent.js
> Fix slider pop-up on advanced search button click

- src/components/registration/RegistrationInput.js
> Change regexes in phone number field

- src/components/clubList/ClubListSider.js
- src/service/StationService.js
> added stations selector for the selected city
